version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ecommerce-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - ecommerce-network

  redis:
    image: redis:7.0-alpine
    container_name: ecommerce-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ecommerce-network

  # Unified Monolith Service
  monolith:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monolith-service
    env_file:
      - ./.env
    # command: npm run dev:monolith # Uncomment for development with hot-reload
    ports:
      - '3000:3000'
    volumes:
      - ./microservices:/usr/src/app/microservices
      - ./libs:/usr/src/app/libs
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis
    networks:
      - ecommerce-network

volumes:
  mongo_data:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge
